export { authService } from './authService';
export { applicationService } from './applicationService';
export { notificationService } from './notificationService';
export { bookingService } from './bookingService';
export type { GeoRegion, GeoDistrict, DoctorFilter } from './bookingService';
export { examinationService } from './examinationService';
export type { Center, CenterFilter } from './examinationService';
export { doctorService } from './doctorService';
export { tariffService } from './tariffService';
export { portfolioService } from './portfolioService';
export { contactService } from './contactService';
export { messageService } from './messageService';
export { faqService } from './faqService';
export { extrasService } from './extrasService';
export { calendarService } from './calendarService';
export { wsService } from './websocketService';
export { laboratoryService } from './laboratoryService';
export type { LabOrder, LabTest, LabCategory } from './laboratoryService';
export { pharmacyService } from './pharmacyService';
export type { Prescription, PrescriptionItem, Medicine } from './pharmacyService';
export { emrService } from './emrService';
export type { MedicalRecord, Allergy, PatientSummary, IcdCode } from './emrService';
export { fileStorageService } from './fileStorageService';
export type { UploadResult } from './fileStorageService';
