export const CANONICAL_MARKERS = [
  { id: 'overview',         label: "Umumiy ma'lumot" },
  { id: 'definition',       label: "Ta'rif" },
  { id: 'etiology',         label: 'Etiologiya' },
  { id: 'pathogenesis',     label: 'Patogenez' },
  { id: 'symptoms',         label: 'Simptomlar' },
  { id: 'diagnosis',        label: 'Diagnostika' },
  { id: 'treatment',        label: 'Davolash' },
  { id: 'stages',           label: 'Bosqichlar' },
  { id: 'classification',   label: 'Klassifikatsiya' },
  { id: 'epidemiology',     label: 'Epidemiologiya' },
  { id: 'risk_factors',     label: 'Xavf omillari' },
  { id: 'prevention',       label: 'Oldini olish' },
  { id: 'prognosis',        label: 'Prognoz' },
  { id: 'complications',    label: 'Asoratlar' },
  { id: 'differential',     label: 'Differensial diagnostika' },
  { id: 'referral',         label: "Yo'llama" },
  { id: 'rehabilitation',   label: 'Reabilitatsiya' },
  { id: 'diet',             label: 'Parhez' },
  { id: 'lifestyle',        label: 'Turmush tarzi' },
  { id: 'red_flags',        label: 'Xavfli belgilar' },
  { id: 'emergency',        label: 'Shoshilinch yordam' },
  { id: 'patient_education',label: "Bemor ta'limi" },
  { id: 'specialists',      label: 'Mutaxassislar' },
  { id: 'labs',             label: 'Laboratoriya' },
  { id: 'imaging',          label: 'Tasvirlash' },
  { id: 'medications',      label: 'Dorilar' },
  { id: 'procedures',       label: 'Muolajalar' },
  { id: 'monitoring',       label: 'Monitoring' },
  { id: 'follow_up',        label: 'Kuzatish' },
  { id: 'clinical_cases',   label: 'Klinik holatlar' },
  { id: 'faq',              label: "Ko'p so'raladigan savollar" },
  { id: 'references',       label: 'Manbalar' },
  { id: 'icd_codes',        label: 'ICD kodlar' },
  { id: 'synonyms',         label: 'Sinonimlar' },
  { id: 'anatomy',          label: 'Anatomiya' },
  { id: 'physiology',       label: 'Fiziologiya' },
  { id: 'history',          label: 'Tibbiyot tarixi' },
  { id: 'guidelines',       label: "Klinik qo'llanmalar" },
] as const;

export type CanonicalMarkerId = (typeof CANONICAL_MARKERS)[number]['id'];
